version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.21.0
  pre_build: 
    commands:
    - echo logging into ecr.
  build:
    commands:
    
    - echo build started on `date`  
    - go build -o myapp gocode/main.go 
    - docker build -t  testimage .
  post_build:
    commands:
    - echo build completed on `date`
    - docker images
